Credit Card 

In [2]:
"Steps"

"""
Generate Fake Data
Preprocess the Data
Feature Engineering
Build and Evaluate Machine Learning Models
Implement Real-Time Detection Logic
"""

'\nGenerate Fake Data\nPreprocess the Data\nFeature Engineering\nBuild and Evaluate Machine Learning Models\nImplement Real-Time Detection Logic\n'

In [3]:
"pip install faker"

'pip install faker'

In [4]:
import pandas as pd
import numpy as np
from faker import Faker
import random
import string

In [5]:
# Initialize Faker
fake = Faker()

In [6]:
# Generating data
num_samples = 2000

In [7]:
# Function to generate customer_id
def generate_customer_id():
    letters = ''.join(random.choices(string.ascii_uppercase, k=2))  # Two random uppercase letters
    numbers = ''.join(random.choices(string.digits, k=3))  # Three random digits
    return letters + numbers

In [8]:
# Generate customer IDs
customer_ids = [generate_customer_id() for _ in range(num_samples)]

In [9]:
# Generate unique 15-digit transaction IDs
transaction_ids = set()
while len(transaction_ids) < num_samples:
    transaction_ids.add(f"{np.random.randint(10**14, 10**15, dtype=np.int64)}")

In [10]:
# Convert set to list
transaction_ids = list(transaction_ids)

In [11]:
# Create the DataFrame
data = {
    'customer_id': customer_ids,
    'customer_name': [fake.name() for _ in range(num_samples)],
    'credit_card_number': [fake.credit_card_number(card_type="visa") for _ in range(num_samples)],
    'amount_deducted': np.random.uniform(1, 500, num_samples),
    'transaction_id': transaction_ids,
    
    'customer_latitude': np.random.uniform(-90, 90, num_samples),
    'customer_longitude': np.random.uniform(-180, 180, num_samples),
    'merchant_latitude': np.random.uniform(-90, 90, num_samples),
    'merchant_longitude': np.random.uniform(-180, 180, num_samples),
    'customer_state': [fake.state_abbr() for _ in range(num_samples)],
    'merchant_state': [fake.state_abbr() for _ in range(num_samples)],
    'transaction_amount': np.random.uniform(1, 500, num_samples),
    'transaction_time': [fake.date_time_this_year() for _ in range(num_samples)],
}

In [12]:
df = pd.DataFrame(data)
df['transaction_date'] = df['transaction_time'].dt.date
df['transaction_hour'] = df['transaction_time'].dt.hour

In [13]:
df

customer_id       customer_name credit_card_number  amount_deducted  \
0          IR007         Derek Woods   4638476807856806       309.323388   
1          BX953  Mitchell Mcfarland   4215326187934387       215.311689   
2          GR125       Richard Baker   4925657732532057       429.845342   
3          WV650          John Jones   4433425203591415       203.885877   
4          LV616         Jeffrey Lee   4171249382509352       280.670560   
...          ...                 ...                ...              ...   
1995       ZK881       Alexis Molina   4108766610366378       319.717170   
1996       NB574       Adam Mcdowell   4195463673597560       205.869831   
1997       PM373        Ricardo Vega   4470746472232959       114.981523   
1998       BB475      Darius Johnson   4608015310764226        52.950868   
1999       PS437         Melvin Holt   4885860593570939       145.669634   

       transaction_id  customer_latitude  customer_longitude  \
0     832594831889396          52.390926         -106.492550   
1     222958730771929         -19.008288          -86.229052   
2     963101750851570         -85.050023          -61.442225   
3     987230814135803         -65.767551          -98.797940   
4     113963170331716          83.281016           50.360711   
...               ...                ...                 ...   
1995  231246667637168          -2.939364         -127.728800   
1996  789302172747201         -40.478355          -92.768848   
1997  536630996186030          75.882673          -57.346933   
1998  519241728458939          13.526013          128.508669   
1999  299727743887509         -44.211070          114.948013   

      merchant_latitude  merchant_longitude customer_state merchant_state  \
0             32.313354          -45.614232             AS             ND   
1             75.413287         -129.474083             FM             UT   
2             78.436930          135.960691             DC             FM   
3             21.175859          -57.181066             MN             NC   
4             21.679360          133.888610             VA             KY   
...                 ...                 ...            ...            ...   
1995         -25.304972         -105.989966             NH             DC   
1996          65.270421          -66.234774             MH             OR   
1997          86.280511         -100.650632             MT             WY   
1998         -74.372153          131.283017             WI             NJ   
1999          50.099075          138.544333             CO             NH   

      transaction_amount    transaction_time transaction_date  \
0             109.881952 2024-05-08 21:21:47       2024-05-08   
1             331.606118 2024-04-13 07:52:50       2024-04-13   
2             402.026115 2024-06-13 20:09:35       2024-06-13   
3             438.500602 2024-07-19 03:44:38       2024-07-19   
4             335.901903 2024-02-02 15:51:22       2024-02-02   
...                  ...                 ...              ...   
1995          499.970828 2024-01-14 23:45:28       2024-01-14   
1996          469.803538 2024-06-02 01:35:19       2024-06-02   
1997          377.748378 2024-01-30 21:53:25       2024-01-30   
1998          186.719322 2024-07-14 01:18:06       2024-07-14   
1999          320.676310 2024-06-03 18:20:13       2024-06-03   

      transaction_hour  
0                   21  
1                    7  
2                   20  
3                    3  
4                   15  
...                ...  
1995                23  
1996                 1  
1997                21  
1998                 1  
1999                18  

[2000 rows x 15 columns]

In [14]:
# Define how many transactions to duplicate
num_to_duplicate = 500  # Number of transactions to repeat

In [15]:
# Choose random customers to duplicate
customers_to_duplicate = np.random.choice(df['customer_id'].unique(), num_to_duplicate, replace=False)

In [16]:
# Create a DataFrame with duplicate transactions
duplicate_data = df[df['customer_id'].isin(customers_to_duplicate)].copy()

In [17]:
# Adjust if there are more rows than needed
# Ensure we only take num_to_duplicate rows
duplicate_data = duplicate_data.head(num_to_duplicate)

In [18]:
# Modify merchant details for duplicates
# Use .loc to set new values
duplicate_data.loc[:, 'merchant_latitude'] = np.random.uniform(-90, 90, duplicate_data.shape[0])
duplicate_data.loc[:, 'merchant_longitude'] = np.random.uniform(-180, 180, duplicate_data.shape[0])
duplicate_data.loc[:, 'merchant_state'] = [fake.state_abbr() for _ in range(duplicate_data.shape[0])]

In [19]:
# Assign new transaction IDs for duplicates to avoid conflicts
duplicate_data.loc[:, 'transaction_id'] = range(num_samples + 1, num_samples + 1 + duplicate_data.shape[0])

In [20]:
# Combine original and duplicated data
df_final = pd.concat([df, duplicate_data], ignore_index=True)

In [21]:
# Define file path for saving the DataFrame
file_path = r'C:\Users\yash.kadam\Downloads\SQL File\credit_data.xlsx'  # Adjust as needed

In [22]:
# Save the DataFrame to an Excel file
df_final.to_excel(file_path, index=False)

In [23]:
"pip install pandas openpyxl"

'pip install pandas openpyxl'

In [24]:
# Load the data
df = pd.read_excel(file_path)

In [25]:
df.head(10)

customer_id       customer_name  credit_card_number  amount_deducted  \
0       IR007         Derek Woods    4638476807856806       309.323388   
1       BX953  Mitchell Mcfarland    4215326187934387       215.311689   
2       GR125       Richard Baker    4925657732532057       429.845342   
3       WV650          John Jones    4433425203591415       203.885877   
4       LV616         Jeffrey Lee    4171249382509352       280.670560   
5       MY121    Timothy Williams    4227587101951023       130.724726   
6       RN160    Michael Schwartz    4210671517252967       431.347588   
7       ZY699       Patrick Evans    4549977439334367       290.275917   
8       BR682         Larry Johns    4833379875199252       279.125864   
9       GW307      Laura Mitchell    4675728378772679       156.997901   

    transaction_id  customer_latitude  customer_longitude  merchant_latitude  \
0  832594831889396          52.390926         -106.492550          32.313354   
1  222958730771929         -19.008288          -86.229052          75.413287   
2  963101750851570         -85.050023          -61.442225          78.436930   
3  987230814135803         -65.767551          -98.797940          21.175859   
4  113963170331716          83.281016           50.360711          21.679360   
5  860933042892565         -73.937205           27.236282          11.934149   
6  816704727127827          86.122766          136.804561          60.658798   
7  460574460021246         -14.960952          -65.187595          45.951450   
8  975578148638960          75.706862          -90.914126         -66.287305   
9  262573613737912         -71.706228           27.161175          31.646739   

   merchant_longitude customer_state merchant_state  transaction_amount  \
0          -45.614232             AS             ND          109.881952   
1         -129.474083             FM             UT          331.606118   
2          135.960691             DC             FM          402.026115   
3          -57.181066             MN             NC          438.500602   
4          133.888610             VA             KY          335.901903   
5           28.878110             CA             OK           13.026814   
6           42.487009             WA             PR          490.163966   
7          -19.011433             WY             DC          455.379586   
8          177.152118             ME             VA          246.403669   
9           81.244404             IA             AS          148.535763   

     transaction_time transaction_date  transaction_hour  
0 2024-05-08 21:21:47       2024-05-08                21  
1 2024-04-13 07:52:50       2024-04-13                 7  
2 2024-06-13 20:09:35       2024-06-13                20  
3 2024-07-19 03:44:38       2024-07-19                 3  
4 2024-02-02 15:51:22       2024-02-02                15  
5 2024-03-10 05:24:36       2024-03-10                 5  
6 2024-06-13 23:02:11       2024-06-13                23  
7 2024-02-21 16:50:18       2024-02-21                16  
8 2024-04-04 19:56:14       2024-04-04                19  
9 2024-04-18 18:24:49       2024-04-18                18

In [26]:
df.describe()  # Provides statistical details like mean, std, min, and quantiles

credit_card_number  amount_deducted  transaction_id  customer_latitude  \
count        2.500000e+03      2500.000000    2.500000e+03        2500.000000   
mean         4.499628e+15       248.832160    4.378638e+14          -1.596201   
min          4.000365e+15         1.578815    2.001000e+03         -89.921290   
25%          4.254645e+15       121.874353    1.442631e+14         -49.928515   
50%          4.497073e+15       247.743765    4.315990e+14          -1.224360   
75%          4.747486e+15       372.331186    7.174556e+14          45.020140   
max          4.999430e+15       499.968816    9.990249e+14          89.959634   
std          2.873950e+14       144.216149    3.198833e+14          53.125021   

       customer_longitude  merchant_latitude  merchant_longitude  \
count         2500.000000        2500.000000         2500.000000   
mean             1.354025          -1.339278            0.264663   
min           -179.622783         -89.952091         -179.965179   
25%            -89.785337         -46.291302          -89.838899   
50%              5.689249          -4.770803           -0.438564   
75%             93.975605          42.724265           91.501705   
max            179.942054          89.857701          179.765134   
std            104.409852          51.687437          105.066284   

       transaction_amount               transaction_time  \
count         2500.000000                           2500   
mean           249.497186     2024-05-01 22:24:11.348000   
min              1.725191            2024-01-01 01:31:12   
25%            125.068116  2024-03-04 01:14:40.750000128   
50%            247.915764            2024-05-03 08:14:26   
75%            377.677950  2024-06-29 19:43:15.249999872   
max            499.970828            2024-08-26 12:33:43   
std            144.109518                            NaN   

                    transaction_date  transaction_hour  
count                           2500        2500.00000  
mean   2024-05-01 10:20:55.680000256          11.55120  
min              2024-01-01 00:00:00           0.00000  
25%              2024-03-03 18:00:00           5.00000  
50%              2024-05-03 00:00:00          12.00000  
75%              2024-06-29 00:00:00          18.00000  
max              2024-08-26 00:00:00          23.00000  
std                              NaN           6.90577

In [27]:
df.info()  # Provides info on DataFrame such as column types, non-null counts, and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   customer_id         2500 non-null   object        
 1   customer_name       2500 non-null   object        
 2   credit_card_number  2500 non-null   int64         
 3   amount_deducted     2500 non-null   float64       
 4   transaction_id      2500 non-null   int64         
 5   customer_latitude   2500 non-null   float64       
 6   customer_longitude  2500 non-null   float64       
 7   merchant_latitude   2500 non-null   float64       
 8   merchant_longitude  2500 non-null   float64       
 9   customer_state      2500 non-null   object        
 10  merchant_state      2500 non-null   object        
 11  transaction_amount  2500 non-null   float64       
 12  transaction_time    2500 non-null   datetime64[ns]
 13  transaction_date    2500 non-null   datetime64[n

In [28]:
df.shape  # Returns a tuple (number of rows, number of columns)

(2500, 15)

In [29]:
df.dtypes  # Returns a Series with data types of each column

customer_id                   object
customer_name                 object
credit_card_number             int64
amount_deducted              float64
transaction_id                 int64
customer_latitude            float64
customer_longitude           float64
merchant_latitude            float64
merchant_longitude           float64
customer_state                object
merchant_state                object
transaction_amount           float64
transaction_time      datetime64[ns]
transaction_date      datetime64[ns]
transaction_hour               int64
dtype: object

In [30]:
# Define unusual hours (late-night, midnight, dawn, twilight)
# Define unusual hours
def get_unusual_rating(hour):
    if 22 <= hour < 24 or 0 <= hour < 8:
        return 1
    return 0

df['unusual_rating'] = df['transaction_hour'].apply(get_unusual_rating)

In [31]:
"pip install geopy"

'pip install geopy'

In [32]:
from geopy.distance import great_circle

# Calculate distance in km
def calculate_distance(row):
    return great_circle(
        (row['customer_latitude'], row['customer_longitude']),
        (row['merchant_latitude'], row['merchant_longitude'])
    ).km

df['distance'] = df.apply(calculate_distance, axis=1)

In [33]:
# Define distance rating
def get_distance_rating(distance):
    if distance > 15000:
        return 1
    elif distance > 10000:
        return 0.75
    elif distance > 5000:
        return 0.5
    else:
        return 0.25

df['distance_rating'] = df['distance'].apply(get_distance_rating)

In [34]:
# Define state rating
df['state_rating'] = (df['customer_state'] != df['merchant_state']).astype(int)

In [35]:
# Define frequency rating
df['limit_rating'] = 0  # Placeholder

In [36]:
# Calculate transaction frequency
frequency = df.groupby(['customer_latitude', 'customer_longitude', 'transaction_date']).size()
frequency = frequency.reset_index(name='frequency')

def get_frequency_rating(row):
    return min(1, frequency[(frequency['customer_latitude'] == row['customer_latitude']) & 
                             (frequency['customer_longitude'] == row['customer_longitude']) & 
                             (frequency['transaction_date'] == row['transaction_date'])]['frequency'].values[0] / 5)

df['limit_rating'] = df.apply(get_frequency_rating, axis=1)

In [37]:
# Calculate average rating
df['average_rating'] = (df['distance_rating'] + df['state_rating'] + df['limit_rating'] + df['unusual_rating']) / 4

# Define fraud risk levels
def get_fraud_risk(average_rating):
    if 0.0 <= average_rating < 0.4:
        return 'low'
    elif 0.4 <= average_rating < 0.7:
        return 'moderate'
    else:
        return 'high'

df['fraud_risk'] = df['average_rating'].apply(get_fraud_risk)

In [38]:
import pickle
from sklearn.ensemble import RandomForestClassifier

# Create and train a model (example)
model = RandomForestClassifier()
# Train model with data here...

# Save the model
with open('model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

label=LabelEncoder()
df['fraud_risk'] = label.fit_transform(df['fraud_risk'])

In [40]:
df['fraud_risk'].unique

<bound method Series.unique of 0       2
1       0
2       2
3       0
4       2
       ..
2495    0
2496    2
2497    2
2498    2
2499    0
Name: fraud_risk, Length: 2500, dtype: int32>

In [41]:
df['fraud_risk'].value_counts()

fraud_risk
2    1693
0     624
1     183
Name: count, dtype: int64

In [42]:
# Define features and target
features = ['distance_rating', 'state_rating', 'limit_rating', 'unusual_rating']
target = ['fraud_risk']
X = df[features]
y = df[target]

In [43]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [44]:
# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

C:\Users\yash.kadam\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=42)

In [45]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [46]:
# Save the trained model and scaler
with open('model.pkl', 'wb') as model_file:
    pickle.dump((model, scaler), model_file)

In [47]:
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

In [48]:
# Evaluate model
y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[188   0   0]
 [  0  48   0]
 [  0   0 514]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       188
           1       1.00      1.00      1.00        48
           2       1.00      1.00      1.00       514

    accuracy                           1.00       750
   macro avg       1.00      1.00      1.00       750
weighted avg       1.00      1.00      1.00       750



In [49]:
# Assuming y_test are the true labels and y_pred are the predicted labels
accuracy = accuracy_score(y_test, y_pred)

# Convert accuracy to percentage
accuracy_percentage = accuracy * 100

print(f"Accuracy: {accuracy_percentage:.2f}%")

Accuracy: 100.00%


In [50]:
# Assuming y_test and y_pred are your true and predicted labels respectively

# Print Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Print Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[188   0   0]
 [  0  48   0]
 [  0   0 514]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       188
           1       1.00      1.00      1.00        48
           2       1.00      1.00      1.00       514

    accuracy                           1.00       750
   macro avg       1.00      1.00      1.00       750
weighted avg       1.00      1.00      1.00       750



In [51]:
# Inspect predicted fraud cases
df_test = X_test.copy()
df_test['true_label'] = y_test
df_test['predicted_label'] = y_pred

# Filter to see actual fraud cases that were predicted as fraud
frauds_detected = df_test[(df_test['true_label'] == 1) & (df_test['predicted_label'] == 1)]
print("Detected Frauds:")
print(frauds_detected)

# Filter to see actual fraud cases that were predicted as non-fraud
missed_frauds = df_test[(df_test['true_label'] == 1) & (df_test['predicted_label'] == 0)]
print("\nMissed Frauds:")
print(missed_frauds)

Detected Frauds:
      distance_rating  state_rating  limit_rating  unusual_rating  true_label  \
1537             0.25             1           0.2               0           1   
497              0.25             1           0.2               0           1   
1606             0.25             1           0.2               0           1   
1103             0.25             1           0.2               0           1   
1936             0.50             0           0.2               0           1   
2271             0.25             0           0.4               0           1   
43               0.25             1           0.2               0           1   
1736             0.25             1           0.2               0           1   
1221             0.50             0           0.4               0           1   
2114             0.75             0           0.4               0           1   
611              0.25             1           0.2               0           1   
1502       

In [52]:
df

customer_id       customer_name  credit_card_number  amount_deducted  \
0          IR007         Derek Woods    4638476807856806       309.323388   
1          BX953  Mitchell Mcfarland    4215326187934387       215.311689   
2          GR125       Richard Baker    4925657732532057       429.845342   
3          WV650          John Jones    4433425203591415       203.885877   
4          LV616         Jeffrey Lee    4171249382509352       280.670560   
...          ...                 ...                 ...              ...   
2495       EH831        Larry Garcia    4893342668069725         3.706827   
2496       XR001     Holly Blackwell    4168130742961340       217.156339   
2497       AZ760          Gary Brown    4014180112068446       279.647751   
2498       RK789   Patricia Melendez    4882626221951772        59.103630   
2499       ZK881       Alexis Molina    4108766610366378       319.717170   

       transaction_id  customer_latitude  customer_longitude  \
0     832594831889396          52.390926         -106.492550   
1     222958730771929         -19.008288          -86.229052   
2     963101750851570         -85.050023          -61.442225   
3     987230814135803         -65.767551          -98.797940   
4     113963170331716          83.281016           50.360711   
...               ...                ...                 ...   
2495             2496           3.927087           70.242649   
2496             2497         -62.454741         -150.526360   
2497             2498          81.172367          172.930672   
2498             2499         -56.214522          -32.876737   
2499             2500          -2.939364         -127.728800   

      merchant_latitude  merchant_longitude customer_state  ...  \
0             32.313354          -45.614232             AS  ...   
1             75.413287         -129.474083             FM  ...   
2             78.436930          135.960691             DC  ...   
3             21.175859          -57.181066             MN  ...   
4             21.679360          133.888610             VA  ...   
...                 ...                 ...            ...  ...   
2495          34.519552         -174.737199             FM  ...   
2496          12.817433          160.182105             VA  ...   
2497          63.494502          171.745051             RI  ...   
2498         -67.576870           82.652240             MN  ...   
2499          83.125922           93.908260             NH  ...   

        transaction_time  transaction_date transaction_hour unusual_rating  \
0    2024-05-08 21:21:47        2024-05-08               21              0   
1    2024-04-13 07:52:50        2024-04-13                7              1   
2    2024-06-13 20:09:35        2024-06-13               20              0   
3    2024-07-19 03:44:38        2024-07-19                3              1   
4    2024-02-02 15:51:22        2024-02-02               15              0   
...                  ...               ...              ...            ...   
2495 2024-05-30 04:24:19        2024-05-30                4              1   
2496 2024-01-28 10:44:47        2024-01-28               10              0   
2497 2024-07-21 03:07:19        2024-07-21                3              1   
2498 2024-04-29 20:23:17        2024-04-29               20              0   
2499 2024-01-14 23:45:28        2024-01-14               23              1   

          distance  distance_rating  state_rating  limit_rating  \
0      5291.437226             0.50             1           0.2   
1     10913.754735             0.75             1           0.2   
2     19237.199947             1.00             1           0.2   
3     10283.359151             0.75             1           0.2   
4      7530.151711             0.50             1           0.2   
...            ...              ...           ...           ...   
2495  12007.902107             0.75             1           0.4   
2496   9386.033508             0.

In [53]:
# Specify the path where you want to save the file
file_path = r'C:\Users\yash.kadam\Downloads\SQL File\credit_data2.xlsx'  # For Windows

# Save DataFrame to the specified path
df.to_excel(file_path, index=False)

In [119]:
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# Assuming model and scaler have been trained
model = RandomForestClassifier(n_estimators=100, random_state=42)
scaler = StandardScaler()

# Save the model and scaler
joblib.dump(model, 'model.pkl')

['model.pkl']

In [121]:
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [127]:
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

file_path = r'C:\Users\yash.kadam\Downloads\SQL File\credit_data2.xlsx'  # For Windows

# Sample data preparation
df = pd.read_excel(file_path)  # Replace with your data file
features = ['distance_rating', 'state_rating', 'limit_rating', 'unusual_rating']
target = 'fraud_risk'
X = df[features]
y = df[target]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scaling features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit scaler on training data
X_test_scaled = scaler.transform(X_test)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# Save model and scaler
joblib.dump(model, 'model.pkl')

['model.pkl']

In [129]:
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']